#!/usr/bin/env bash
set -e

# check if root
if [[ $EUID -ne 0 ]]; then
  printf 'Script must be executed as root.\n'
  exit 1
fi

clean_files() {
  files=(
    '/etc/X11/xinit/xinitrc.d/nvidia'
    '/etc/X11/xorg.conf.d/00-avoid-glamor.conf'
    '/etc/X11/xorg.conf.d/99-nvidia.conf'
    '/etc/X11/xorg.conf'
  )

  for file in "${files[@]}"; do
    if [[ -h $file ]]; then
      echo "Deleting $file"
      rm -f "$file"
    elif [[ -f $file ]]; then
      echo "Backing up $file"
      cp "$file" "$file.fedora-prime.bak"
      rm -f "$file"
    fi
  done
}

install_dir='/etc/fedora-prime'
nvidia32_lib_file='/etc/ld.so.conf.d/nvidia-lib.conf'
nvidia64_lib_file='/etc/ld.so.conf.d/nvidia-lib64.conf'

case $1 in
  nvidia )
    printf "Switching to %s..." "$1"
    clean_files
    bus_id=$(lspci | grep NVIDIA | awk '{print $1 + 0}')
    sed "s/bus_id/$bus_id/g" $install_dir/xorg.conf.template > /etc/X11/xorg.conf
    ln -s $install_dir/xinitrc.nvidia /etc/X11/xinit/xinitrc.d/nvidia
    echo '/usr/lib64/nvidia' > $nvidia64_lib_file
    if [[ -f $nvidia32_lib_file ]]; then
      echo '/usr/lib/nvidia' > $nvidia32_lib_file
    fi
    ;;
  intel )
    printf "Switching to %s..." "$1"
    clean_files
    echo '/usr/lib64' > $nvidia64_lib_file
    if [[ -f $nvidia32_lib_file ]]; then
      echo '# disabled by fedora-prime' > $nvidia32_lib_file
    fi
    ;;
  * )
    printf "Usage:\n  %s intel|nvidia\n" "$(basename "$0")"
    exit 1
    ;;
esac

printf "Running ldconfig...\n"
ldconfig

printf "Switching to %s completed.\n" "$1"
printf "Please logout for changes to take effect.\n"
