#!/usr/bin/env bash
set -e

# check if root
if [[ $EUID -ne 0 ]]; then
  printf 'Script must be executed as root.\n'
  exit 1
fi

clean_files() {
  files=(
    '/etc/X11/xinit/xinitrc.d/nvidia'
    '/etc/X11/xorg.conf.d/00-avoid-glamor.conf'
    '/etc/X11/xorg.conf.d/99-nvidia.conf'
    '/etc/X11/xorg.conf'
  )

  for file in "${files[@]}"; do
    if [[ -h $file ]]; then
      printf "Deleting %s\n" "$file"
      rm -f "$file"
    elif [[ -f $file ]]; then
      printf "Backing up %s as %s\n" "$file" "$file.fedora-prime.bak"
      cp "$file" "$file.fedora-prime.bak"
      rm -f "$file"
    fi
  done
}

install_dir='/etc/fedora-prime'
nvidia32_lib_file='/etc/ld.so.conf.d/nvidia-lib.conf'
nvidia64_lib_file='/etc/ld.so.conf.d/nvidia-lib64.conf'

case $1 in
  nvidia )
    clean_files
    bus_id=$(lspci | grep NVIDIA | awk '{print $1 + 0}')
    sed "s/bus_id/$bus_id/g" $install_dir/xorg.conf.template > /etc/X11/xorg.conf
    ln -s $install_dir/xinitrc.nvidia /etc/X11/xinit/xinitrc.d/nvidia
    printf '/usr/lib64/nvidia' > $nvidia64_lib_file
    if [[ -f $nvidia32_lib_file ]]; then
      printf '/usr/lib/nvidia' > $nvidia32_lib_file
    fi
    # add desktop file (thanks, Arch wiki!!) 
    cp $install_dir/gdm_display_setup.desktop /usr/share/gdm/greeter/autostart/gdm_display_setup.desktop
    
    ldconfig
   	#remove link to libwfb in nvidia installation dir. This library is already provided by xorg
   	#and anyway it would fail with the nvidia library 
    rm -f /usr/lib64/nvidia/xorg/modules/libwfb.so 
    #link libGL.so.1 to point to the nvidia libraries 
	ln -sf /usr/lib64/nvidia/libGL.so.1 /usr/lib64/libGL.so.1
	ln -sf /usr/lib/nvidia/libGL.so.1 /usr/lib/libGL.so.1
    
    ;;
  intel )
    clean_files
    printf '/usr/lib64' > $nvidia64_lib_file
    if [[ -f $nvidia32_lib_file ]]; then
      printf '/usr/lib' > $nvidia32_lib_file
    fi
    #remove desktop file
    rm -f /usr/share/gdm/greeter/autostart/gdm_display_setup.desktop
    ldconfig
    ;;
  * )
    printf "Usage:\n  %s intel|nvidia\n" "$(basename "$0")"
    exit 1
    ;;
esac


printf "Successfully switched to %s.\n" "$1"
printf "Please logout for changes to take effect.\n"
